/** 每个用于搜索查询的 ISO-3166-1 alpha-2 市场代码的规范显示名称。 */
export const MARKET_NAMES: Record<string, string> = {
  ae: '阿联酋',
  sa: '沙特阿拉伯',
  kw: '科威特',
  qa: '卡塔尔',
  bh: '巴林',
  om: '阿曼',
  eg: '埃及',
  gb: '英国',
  us: '美国',
  ca: '加拿大',
  au: '澳大利亚',
  de: '德国',
  fr: '法国',
  nl: '荷兰',
  sg: '新加坡',
  in: '印度',
  pk: '巴基斯坦',
  ng: '尼日利亚',
  ke: '肯尼亚',
  za: '南非',
  ch: '瑞士',
  br: '巴西',
};